[tools]
python = "latest"

[env]
# Use the project name derived from the current directory
PROJECT_NAME = "{{ config_root | basename }}"

# Automatic virtualenv activation
_.python.venv = { path = ".venv", create = true }

[tasks.install]
description = "Install dependencies"
alias = "i"
run = "uv pip install -r requirements.txt"

#[tasks.run]
#description = "Run the application"
#run = "python main.py"

#[tasks.test]
#description = "Run tests"
#run = "pytest tests/"

#[tasks.lint]
#description = "Lint the code"
#run = "ruff src/"

[tasks.info]
description = "Print project information"
run = '''
echo "Project: $PROJECT_NAME"
echo "Virtual Environment: $VIRTUAL_ENV"
'''